### ISSUE TITLE
mask comes very slow after being triggered several times in a sessions

### ISSUE THREAD

**Issue by haubourg** [aeag/mask#10]

**Comment by haubourg** [comment]
probably related to a memory leak, confirmed in v 2.6.1 here

**Comment by haubourg** [comment]
confirmed in 2.8.1 too. 
The more unzoomed, the higher leak is .. (4 masks and we lead to 6 Go...)

**Comment by vpicavet** [comment]
Can you provide a data sample with complete test case showing the bug ?

**Comment by haubourg** [comment]
I can't reproduce it by now. Source project has been changed. Please do no work on this now.
