### ISSUE TITLE
rule-based labelling - mask does not work

### ISSUE THREAD

**Issue by szooon1** [aeag/mask#115]
The mask does not cover labels on layers that have rule-based labels. Is it possible to fix this somehow?

**Comment by xcaeag** [comment]
thanks for the remark. While waiting for a new version, you can do the following:

The plugin is only an aid to building the mask, and you can do without it (see the documentation for that).

Depending on the configuration, the plugin will modify certain labeling parameters, including the 'show label' parameter. Look at the expression there (for a layer that does not have a labeling rule, but filtered by the plugin), and copy it to each of the rules. The expression only allows us to determine whether the geometry is 'in the mask' or not. Here the 2154 is the layer projection code.

![image](https://github.com/aeag/mask/assets/7790344/a5e945f5-d82d-45f7-8932-610de5a1e5e1)

**Comment by xcaeag** [comment]
if you can, you can test 1.10.4 version, package here : https://github.com/aeag/mask/releases/tag/v1.10.4 before its publication on qgis repository

**Comment by szooon1** [comment]
It looks like it's working!BBêWillI'll be I'll be testing it some more, thank you!

**Comment by szooon1** [comment]
It seems to be working! I'll be testing it some more, thank you!
