### ISSUE TITLE
Trouble with do_mask from external plugin

### ISSUE THREAD

**Issue by haubourg** [aeag/mask#25]
In some use cases, there seem to be some unicode trouble with layer's name testing on line aeag_mask.py:482: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal

It seems to work well but throws a trace and we have troubles in generating correct layer's title (encoding miscconversion)

**Comment by xcaeag** [comment]
On repart à zéro hein !
Si ça recommence, tu sauras me trouver.
