### ISSUE TITLE
Mask does not update in Atlas preview 

### ISSUE THREAD

**Issue by haubourg** [aeag/mask#43]
The initial mask remains the same

**Comment by mhugo** [comment]
I can't reproduce

**Comment by haubourg** [comment]
Bon, c'est pire que prévu. la prévisu de l'atlas ne mettait rien à jour, mais j'avais oublié d'activer l'atlas sur la carte choisie (au passage, un warning serait pas idiot, si atlas activé, et aucun item avec atlas appliqués > warning). 
Depuis que j'ai réactivé l'option, qgis crash directement à l'activation de l'Atlas. 
Le plugin First Aid me permet d'apercevoir avant le crash que la géométrie est null.

**Comment by haubourg** [comment]
solved
