### ISSUE TITLE
current master triggers crashes qgis when creating a composer

### ISSUE THREAD

**Issue by haubourg** [aeag/mask#47]
steps to reproduce:
use 
-qgis master 2.130-39 (commit  6035d98 )
- hotlink master https://github.com/aeag/mask/commit/25e201e91c676d270e7667ebe0932fa6aacea068

add one polygon layer, 
create a mask, 
try to create a composer > crash

**Comment by mhugo** [comment]
Confirmed. Working on it

**Comment by mhugo** [comment]
Should be fixed now
https://github.com/qgis/QGIS/pull/2556

**Comment by haubourg** [comment]
ok, will test tomorrow with nightlies

**Comment by haubourg** [comment]
solved
