### ISSUE TITLE
Some part of the selection excluded from the mask

### ISSUE THREAD

**Issue by dominvepf** [aeag/mask#54]
Hi and thanks for your wonderful plugin, it looks amazing. I am completely new to GIS and so please excuse me if this is something obvious.

I have a vector layer and a bing map layer beneath it. I want to only highlight the content of my vector layer.when I create the mask some areas in the center of the vector layer are not included. See hole in the mask.png to see what I mean
<img width="2560" alt="hole in the mask" src="https://cloud.githubusercontent.com/assets/18558211/14648522/0298e7fe-0663-11e6-8661-5e6553bfcbe7.png">

Steps to repro:
0) start with a vector and a bing map behind it
<img width="2560" alt="step 0 - layer and map" src="https://cloud.githubusercontent.com/assets/18558211/14648603/5fe928a6-0663-11e6-911f-ad54f0bad649.png">

1) Select all items on a vector layer
<img width="2560" alt="step one select all" src="https://cloud.githubusercontent.com/assets/18558211/14648545/1bb7007c-0663-11e6-8c95-9d0bba323be9.png">

2) Create a mask
<img width="2560" alt="step 2 create a mask" src="https://cloud.githubusercontent.com/assets/18558211/14648566/32b13d38-0663-11e6-910a-3a4659858ecf.png">

3) accept default since it all looks good
<img width="2560" alt="step 3 accept default" src="https://cloud.githubusercontent.com/assets/18558211/14648625/79ba710e-0663-11e6-8dac-19f95b0f703e.png">

4) You get the mask with a hole in it shown in description of problem.

Can you help me figure it out?

Thanks

**Comment by haubourg** [comment]
Hi, 
please check if geometry is valid in your vector layer. I suspect you have a geometry error preventing QGIS from dissolving these features together. 
Cheers
Régis

**Comment by dominvepf** [comment]
Hi, there must have been an error in the geometry. When  I tried to manually merge every vector to make one big one, it failed. Fortunately all the outside vectors were correct, I was able to merge them and then create a new polygon joining them together, when I use that layer as the mask it works. Sorry for the false alarm and thanks for the help
