### ISSUE TITLE
mask layer locked in item map composer is not visible after reloading saved project 

### ISSUE THREAD

**Issue by jdlom** [aeag/mask#56]
After having locked the mask layer in the locked layers for map item, when we reopen the saved project and we active again the atlas, the mask layer does not appear anymore in the locked layers list.

You have to relock the layers by selecting them manually in the layers panel.

**Comment by haubourg** [comment]
Confirmed here in 2.14 and master, thanks for the report. 
I suspect this is related to Memory layer Saver that restores layers after composer is initialized.

**Comment by haubourg** [comment]
Not related to memory layer saver, a classical memory layer is restored and visible in Composer's layers on reload.

**Comment by xcaeag** [comment]
sorry,
reopen the ticket if the error still occurs in 3.x !
