### ISSUE TITLE
Save mask to shapefile

### ISSUE THREAD

**Issue by linar-jether** [aeag/mask#57]
When saving the mask layer to a shapefile the result is just the shape of the mask, instead of the inverted shape. 
How can i save the inverted shape (mask) instead of the shap?

**Comment by xcaeag** [comment]
A mask is truly a polygon which one applies the style "inverted polygon".
The shapefile format not storing the styles, you must save it (the only style) in QML format for example, next to the shapefile.
Or save Style+Layer in a Geopackage format.
