### ISSUE TITLE
"Create mask" greyed out

### ISSUE THREAD

**Issue by Bernd-Vogelgesang** [aeag/mask#58]
It seems that after  updating to 2.16, the Mask plugin does not seem to work anymore for me. Unfortunately I can not tell for sure, cause it was the first time that I used the plugin two weeks ago.

Anyway, now when I try to create a mask, the button in the toolbar and the entry in the menu are greyed out.
Unistalling, removing from the plugins folder, reinstalling lead to nothing.

No difference for a new project or an existing one: after start-up, the button ist greyed out, no matter what layer I activate.

Any hints how to resolve the problem?

Linux Mint 17.2

**Comment by haubourg** [comment]
Hi Bernd, you confirm you have a polygon selected in the active layer? Any trace in message log?

**Comment by Bernd-Vogelgesang** [comment]
Hi Régis, 
I'm awfully sorry for the noise. Obviously on first usage I selected the feature intuitively, but last time I lost my senses it seems. Everything fine, thanx for the nice plugin which helps me to make a nice map :)
Cheers,
Bernd
