### ISSUE TITLE
Can't click on the icon mask 

### ISSUE THREAD

**Issue by Corsican** [aeag/mask#62]
Hi evryone ! I just download mask puglin on QGIS (2.18.9) but the icon on the toolbar is grey and I can't click on it so I can't use it ! The puglin is 1.5.1 version. Can you help me ?

**Comment by xcaeag** [comment]
Hi,
Even if you have previously selected a polygon?

![tuto-mask](https://user-images.githubusercontent.com/7790344/27429396-3388a8de-5745-11e7-807c-fab424e1bdf4.gif)

**Comment by Corsican** [comment]
Supeeeeeer ça marche ! Merci beaucoup super puglin ça évite de passer par Paint ou autre ! Très contente

**Comment by Corsican** [comment]
Greeeat ! It's Ok now. Awsome plugin
