### ISSUE TITLE
Couldn't load plugin 'mask' in qgis 3.0

### ISSUE THREAD

**Issue by antoniusz** [aeag/mask#67]
Couldn't load plugin 'mask' due to an error when calling its classFactory() method 

ImportError: cannot import name 'QgsAtlasComposition' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 336, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/toni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/mask/__init__.py", line 22, in classFactory
    from .aeag_mask import aeag_mask
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/toni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/mask/aeag_mask.py", line 39, in 
    from qgis.core import (QgsExpression, QgsExpressionFunction, QgsAtlasComposition, QgsGeometry,
ImportError: cannot import name 'QgsAtlasComposition'

Python version: 3.5.3 (default, Jan 19 2017, 14:11:04) [GCC 6.3.0 20170118] 
QGIS version: 3.0.0-Girona Girona, 529903c 

Python Path:
/usr/share/qgis/python
/home/toni/.local/share/QGIS/QGIS3/profiles/default/python
/home/toni/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python35.zip
/usr/lib/python3.5
/usr/lib/python3.5/plat-x86_64-linux-gnu
/usr/lib/python3.5/lib-dynload
...
/usr/lib/python3/dist-packages
/usr/local/lib/python3.5/dist-packages
/home/toni/.local/share/QGIS/QGIS3/profiles/default/python
/home/toni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2streetview
/home/toni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2streetview/res
.
/home/toni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/mmqgis/forms
/home/toni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/vrtbuilderplugin
/home/toni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/vrtbuilderplugin/vrtbuilder

**Comment by antoniusz** [comment]
duplicate of #66

sorry

**Comment by xcaeag** [comment]
Yes, this plugin has not really been ported to 3.0.
We are preparing a version that will work at least, without the atlas, while waiting to find a solution.

In the meantime, playing with styles (inverted polygon) and expressions in filters (attribute ($ currentfeature, 'my_id') = attribute (@atlas_feature, 'my_id'))) can help (for Atlas).

**Comment by arthuragone** [comment]
I experience the same bug 

> Couldn't load plugin 'mask' due to an error when calling its initGui() method 

TypeError: QgsLayoutManager.layoutByName(): argument 1 has unexpected type 'QgsPrintLayout' 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 344, in startPlugin
    plugins[packageName].initGui()
  File "C:/Users/AVIGNACQ/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\mask\aeag_mask.py", line 226, in initGui
    self.on_layout_added(layout)
  File "C:/Users/AVIGNACQ/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\mask\aeag_mask.py", line 349, in on_layout_added
    layout = QgsProject.instance().layoutManager().layoutByName(layoutName)
TypeError: QgsLayoutManager.layoutByName(): argument 1 has unexpected type 'QgsPrintLayout'

Could you give me more info about the trick with styles?

**Comment by xcaeag** [comment]
I will try to record a tutorial as soon as possible !

**Comment by xcaeag** [comment]
**Combine mask and Atlas (without the plugin)**

The principle is to use the renderer "inverted polygons" + "Rule-based" to filter the current mask feature, with the style "Shapeburst fill".

The 'mask' filter of the rule :  
   ` attribute($currentfeature, 'the_primary_key_field') =  attribute(@atlas_feature , 'the_primary_key_field') `

The label layer filter if neaded : 
    `contains(@atlas_geometry, $geometry)`

![tuto-mask](https://user-images.githubusercontent.com/7790344/49210169-ad32f800-f3bc-11e8-865d-c00dd9b77b76.gif)
