### ISSUE TITLE
mask et atlas

### ISSUE THREAD

**Issue by f2d2r2** [aeag/mask#83]
Bonjour,
Nous sommes en modification simplifiée du PLUi de notre territoire. A cet effet je dois générer des cartes par commune selon une grille pour faire mon atlas.
Or quand je créé un mask sur une communes (par sélection manuelle) et que j'active l'atlas le mask s'active sur la grille et plus sur la commune.
Y a t-il une solution ?
Cordialement

**Comment by f2d2r2** [comment]
Voici des captures d'écran pour illustrer ma demande
Merci
[
![commune](https://user-images.githubusercontent.com/86049570/122370809-ab6fb680-cf5f-11eb-8c84-5269b66284da.PNG)
](url)
[
![grille](https://user-images.githubusercontent.com/86049570/122370932-c17d7700-cf5f-11eb-8bf0-f1adcfbee09c.PNG)
](url)

**Comment by xcaeag** [comment]
Bonjour, 

j'ai compris ceci : vous ne souhaitez pas que le masque s'adapte à la couche de couverture de l'atlas, et reste sur votre commune.
Dans la dernière version du plugin, encore 'expérimentale'  (1.10.0-beta1) une option permet de décorréler atlas et masque. 
Avez-vous la possibilité de l'installer et tester ?

**Comment by f2d2r2** [comment]
Bonjour,
En effet, je souhaite que le masque reste sur la commune et pas sur l’atlas !
J’ai effectivement la possibilité d’installer la nouvelle version du plugin mais comment ?
En tout cas merci de votre réactivité
f.Fraudeau

De : Xavier Culos ***@***.***>
Envoyé : jeudi 17 juin 2021 11:43
À : aeag/mask ***@***.***>
Cc : Frédéric Fraudeau ***@***.***>; Author ***@***.***>
Objet : Re: [aeag/mask] mask et atlas (#83)


Bonjour,

j'ai compris ceci : vous ne souhaitez pas que le masque s'adapte à la couche de couverture de l'atlas, et reste sur votre commune.
Dans la dernière version du plugin, encore 'expérimentale' (1.10.0-beta1) une option permet de décorréler atlas et masque.
Avez-vous la possibilité de l'installer et tester ?

**Comment by xcaeag** [comment]
Simplement cocher l'option [Afficher les extensions expérimentales], dans l'onglet 'configuration' de la fenêtre de gestion des extensions. Puis mettre à jour l'extension j'imagine !

**Comment by f2d2r2** [comment]
Je vous remercie énormément pour ces conseils. J'ai mis à jour le plugin et ai pu générer mes cartes correctement !!!
Merci encore et bonne journée !
Cordialement

**Comment by xcaeag** [comment]
Merci de tester, le plugin passera bientôt en 'non expérimental', grâce à vous !
