### ISSUE TITLE
Rotation map issue

### ISSUE THREAD

**Issue by Zampaski** [aeag/mask#84]
Hi,
Great job witgh this but I find out that the mask seems affetected while introducing a rotation into the map.
![rotation issue](https://user-images.githubusercontent.com/86717973/123945259-4031d580-d99e-11eb-8c42-16eba25602f5.jpg)

**Comment by xcaeag** [comment]
Thank you,

it's strange, i can't reproduce the problem.
Is this behavior the same with an inverted polygon style, without the use of the mask ? 

Can you give more details (versions, contours of the expected mask, is it the main window or the composer.. ) ?

**Comment by xcaeag** [comment]
no news, may be a problem related to a particular version.
